### ISSUE TITLE
Create and use file for logs

### ISSUE THREAD

**Issue by AnatoliiStepaniuk** [Oleg1224222222/game2048#1]
Format: **CSV**
(for example, `logs.csv`)

This file will always append all logs that your program has ever written (it is never erased, only added to at the end).

Example file (the first row is the column header):

```
timestamp,message
2024-05-11 14:30:25,User started the Game
2024-05-11 14:32:10,User X chose the (2,2) cell
2024-05-11 14:35:45,User Y chose the (3,3) cell
```

The timestamp format - of your choice.

**Comment by Oleg1224222222** [comment]
![Снимок1](https://github.com/Oleg1224222222/game2048/assets/170743123/a17db33e-71c8-4265-93ea-70f0c9d89d66)
![Снимок22](https://github.com/Oleg1224222222/game2048/assets/170743123/a5d4e74c-aa99-4e6e-8129-f1d38343bed1)
