### ISSUE TITLE
Create and use file for saving game history

### ISSUE THREAD

**Issue by AnatoliiStepaniuk** [Oleg1224222222/game2048#2]
The file that saves the number of wins of each player.
Format: **JSON** (for example, `wins.json`)

```
{
   "wins": {
      "X": 3,
      "O": 0
   }
}
```

At the beginning of the game, you need to read the win history from this file.

After each game, update it so that the program remembers the win history even if the computer is restarted.
Use some libraries for reading and writing these files, as manually formatting them might not be very convenient.

**Comment by Oleg1224222222** [comment]
Результаті гри зберігаються в файлі game_results.csv
